config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'region/get_city'

  resources :stores
  root "stores#index"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)



    if user.nil?
      can :read, Store

    elsif user.role? "admin"
      can :manage, :all

    elsif user.role? "user"
      can :read, Store
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/permission.rb
class Permission < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :permissions
  has_many :users,through: :permissions
end

app/models/store.rb
class Store < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :permissions
  has_many :roles, through: :permissions


  def role? role
    self.roles.pluck(:name).include? role
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

rescue_from CanCan::AccessDenied do
  redirect_to root_path, alert: "you are not authorized to access this page"
end



protected
def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up,keys: [:username])

end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :authenticate_user!, except: [:index,:show]
  load_and_authorize_resource
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    if params[:search]

        session[:city_name] = "#{params[:search].downcase}"
        @stores = Store.all.where('lower(city) = ?',"#{session[:city_name]}")
        @downcased = Store.pluck(:city).map(&:downcase)
        unless @downcased.include? "#{session[:city_name]}"
           flash.now[:alert] = "No stores for the city '#{session[:city_name]}' yet! Please seach something else.. "
        end
    elsif session[:city_name]
      flash.now[:notice]= "you have selected '#{session[:city_name]}' as your city."
      @stores = Store.all.where('lower(city) = ?',"#{session[:city_name]}")
      @downcased = Store.pluck(:city).map(&:downcase)
      unless @downcased.include? "#{session[:city_name]}"
         flash.now[:alert] = "No stores for the city '#{session[:city_name]}' yet! Please seach something else.. "
      end

    else
      flash.now[:notice] = "please select a city to begin!"
    end
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def city

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name, :street, :city, :zip, :phone, :website)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/layouts/_aboutModal.html.erb
<!-- Modal -->
<div class="modal fade" id="aboutModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">About</h4>
      </div>
      <div class="modal-body" style="color:blue">
        <h1 >Project: Online Store Listing</h1>
        <p> You'll be building a simple online listing of stores with admin to control the stores. The project
            consist of 2 modules that covers CRUD features -
            1. The customer facing that lists all the stores in a selected geographical location
            2. An admin screen with a form to Add, Update, and Delete a store</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

      </div>
    </div>
  </div>
</div>

app/views/layouts/_contactModal.html.erb
<!-- Modal -->
<div class="modal fade " id="contactModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Contact</h4>
      </div>
      <div class="modal-body text-center" style="color:blue">
        <h1>Ajinkya Devasthali</h1>
        <h3>https://github.com/ajex13</h3>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

      </div>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% if notice %>
	<div class='alert alert-success alert-dismissable'>
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
		<%= notice %>
	</div>
<% end %>

<% if alert %>
	<div class='alert alert-danger alert-dismissable'>
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
		<%= alert %>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HashStores</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="padding-top: 100px;">
    <%= render 'components/navbar' %>
    <%= render('layouts/messages.html.erb') %>
    <%= render 'layouts/aboutModal' %>
    <%= render 'layouts/contactModal' %>
    <%= yield %>
  </body>
</html>

app/views/stores/_form.html.erb
<%= form_for(store) do |f| %>
  <% if store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :street %>
    <%= f.text_field :street %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :zip %>
    <%= f.text_field :zip %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label :website %>
    <%= f.text_field :website %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<% if can? :create, Store.new %>
<pre>Howdy, <strong>admin</strong>! You're our rockstar so you get to do all of this:
  1) Create new store
  2) Update existing store
  3) Delete a store (remember,with great power..)
  <%= button_to 'New Store', new_store_path, class: "btn btn-default", method: :get %>
</pre>
<% end %>



<%= form_tag( stores_path, :method => "get", role:"search") do %>
      <div class="input-group">
        <%= text_field_tag :search, params[:search], placeholder: "Search City" ,class:"form-control main-input", :required => "true" %>
        <span class="input-group-btn">
         <%= submit_tag "Search", :name => nil,class: 'btn btn-default' %>

        </span>
      </div>
<% end %>

<br>


<% if session[:city_name] && (@downcased.include? "#{session[:city_name]}") %>
<h1>Stores</h1>
<pre>
<table class="table table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Street</th>
      <th>City</th>
      <th>Zip</th>
      <th>Phone</th>
      <th>Website</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= store.name %></td>
        <td><%= store.street %></td>
        <td><%= store.city %></td>
        <td><%= store.zip %></td>
        <td><%= store.phone %></td>
        <td><%= store.website %></td>
        <!--links-->
        <td><%= link_to 'Show', store %></td>
        <% if can? :create, Store.new %>
        <td><%= link_to 'Edit', edit_store_path(store) %></td>
        <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        <!--links-->
      </tr>
    <% end %>
  </tbody>
</table>
</pre>
<% else %>
<%= render 'components/jumbotron' %>
<% end %>
<br>

app/views/stores/new.html.erb
<h1>New Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<div class="text-center">
<h1>
  <strong><%= @store.name %></strong>
</h1>
<pre>
<table class="table table-bordered">


    <tr>
      <td><strong>Street:</strong></td>
      <td><%= @store.street %></td>
    </tr>

      <tr>
        <td><strong>City:</strong></td>
        <td><%= @store.city %></td>
      </tr>

        <tr>
          <td><strong>Zip:</strong></td>
          <td><%= @store.zip %></td>
        </tr>

          <tr>
            <td><strong>Phone:</strong></td>
            <td><%= @store.phone %></td>
          </tr>

            <tr>
              <td><strong>Website:</strong></td>
              <td><%= @store.website %></td>
            </tr>

</table>
</pre>

</div>

<span class="links-in-show">
<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>
</span>